on:
  push:
    branches:
      - '**'

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install werf
        uses: werf/actions/install@v1.2
        
      - name: Run script
        run: |
          . $(werf ci-env github --as-file) 
